---
name: Generate Spring Boot property migration recipes

on:
  workflow_dispatch: {}
  # Disabled as the generator here is incomplete, as seen for Spring Boot 4.0, as compared to internal tool.
#  schedule:
#    - cron: 0 11 * * TUE

jobs:
  update-migrations:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.repository_owner == 'openrewrite'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v5

      # Generate Spring Boot property migrations recipes
      - name: Create jar and copy dependencies
        run: ./gradlew generatePropertyMigrationRecipes

      # Create pull request
      - name: Timestamp
        run: echo "NOW=$(date +'%Y-%m-%dT%H%M')" >> $GITHUB_ENV
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: migrations/${{ env.NOW }}
          title: "[Auto] Spring Boot property migration recipes as of ${{ env.NOW }}"
          body: |
            [Auto] Spring Boot property migration recipes as of ${{ env.NOW }}.
          commit-message: "[Auto] Spring Boot property migration recipes as of ${{ env.NOW }}"
          labels: enhancement
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
